services:
  - type: web
    name: metabase
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    port: 10000
    healthCheckPath: /api/health
    envVars:
      - key: MB_DB_FILE
        value: /tmp/metabase.db
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx384m -Xms128m

