services:
  - type: web
    name: metabase
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    port: 10000
    envVars:
      - key: PORT
        value: 10000
      - key: MB_JETTY_PORT
        value: 10000
      - key: MB_JETTY_HOST
        value: 0.0.0.0
      - key: MB_DB_FILE
        value: /tmp/metabase.db
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx384m -Xms128m

